version: 2.1

jobs:
  php81:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run: composer require phpunit/phpunit phpstan/phpstan --dev
      - run: php vendor/bin/phpunit
      - run: php vendor/bin/phpstan analyze -c phpstan.legacy.neon
  php82:
    docker:
      - image: cimg/php:8.2
    steps:
      - checkout
      - run: composer require phpunit/phpunit phpstan/phpstan --dev
      - run: php vendor/bin/phpunit
      - run: php vendor/bin/phpstan analyze
  php83:
    docker:
      - image: cimg/php:8.3
    steps:
      - checkout
      - run: composer require phpunit/phpunit phpstan/phpstan --dev
      - run: php vendor/bin/phpunit
      - run: php vendor/bin/phpstan analyze
  php84:
    docker:
      - image: cimg/php:8.4
    steps:
      - checkout
      - run: composer require phpunit/phpunit phpstan/phpstan --dev
      - run: php vendor/bin/phpunit
      - run: php vendor/bin/phpstan analyze

workflows:
  version: 2
  workflow:
    jobs:
      - php81
      - php82
      - php83
      - php84
